import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/component/header/Header";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Domza Motoservis Tracker",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        {/*<Footer /> - No need for footer currently, might be added later */}
      </body>
    </html>
  );
}
