import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import Header from "@/component/Header";
import Footer from "@/component/Footer";
import { NextUIProvider } from "@nextui-org/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Domza Motoservis Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextUIProvider className="min-h-screen flex flex-col justify-between">
          <SessionProvider>
            <Header />
            {children}
            {/*<Footer /> - No need for footer currently, might be added later */}
          </SessionProvider>
        </NextUIProvider>
      </body>
    </html>
  );
}
